version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: academia-postgres
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_contraseña_segura
      POSTGRES_DB: academia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: