services:
  postgres:
    image: postgres:16
    container_name: app-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin-jfdg-admin
      POSTGRES_DB: academia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: