# Production configuration - disables verbose logging for security and performance
app:
  logging:
    response-body:
      enabled: false         # Disable response body logging in production
      max-length: 500        # Reduced max length if enabled
      include-size: false    # Don't log response sizes in production

# Reduce logging verbosity in production
logging:
  level:
    root: WARN
    app: INFO
    app.config.ApiLoggingInterceptor: INFO  # Reduce from DEBUG to INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN 