spring:
 # La config del DataSource esta en el docker file
  datasource:
    url: jdbc:postgresql://localhost:5432/academia_db
    username: admin
    password: admin-jfdg-admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create
  application:
    name: app
  docker:
    compose:
      file: docker-compose.db.yml

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 hours in milliseconds

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  packages-to-scan: app.rest